[tox]
envlist =
    py310-django{42,50,51}
    py311-django{42,50,51}
    py312-django{42,50,51}
    py313-django{42,50,51,60}
    py314-django{42,50,51,60}

[testenv]
deps =
    django42: Django>=4.2,<4.3
    django50: Django>=5.0,<5.1
    django51: Django>=5.1,<5.2
    django60: Django>=6.0,<6.1
commands = python runtests.py

[flake8]
ignore = E265,E501
